# Generated by Django 2.2.3 on 2019-07-12 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('current_level_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('points', models.CharField(default='0', max_length=10)),
                ('email', models.CharField(max_length=200)),
                ('rollno', models.CharField(max_length=9)),
                ('referral', models.CharField(default=0, max_length=100)),
                ('referral_count', models.IntegerField(default=0)),
                ('current_level', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='game.Level')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
