# Generated by Django 2.2.3 on 2019-07-12 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='rollno',
            new_name='roll',
        ),
    ]
