# Generated by Django 2.2.2 on 2019-08-04 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190712_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='bonus_attempted',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='roll',
            field=models.CharField(default='0', max_length=9),
        ),
    ]
