# Generated by Django 2.2.1 on 2019-12-25 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_player_bonus_level_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_registered',
            field=models.BooleanField(default=False),
        ),
    ]
