# Generated by Django 2.2.2 on 2019-08-03 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='audiofile',
            field=models.FileField(blank=True, null=True, upload_to='media/', verbose_name=''),
        ),
        migrations.AddField(
            model_name='level',
            name='is_bonus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='level',
            name='videofile',
            field=models.FileField(blank=True, null=True, upload_to='media/', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='level',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
