# Generated by Django 2.0.13 on 2019-08-08 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20190803_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static'),
        ),
    ]
