# Generated by Django 2.2.1 on 2019-12-02 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20190808_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='answer',
            field=models.TextField(max_length=120),
        ),
    ]
