# Generated by Django 2.2.1 on 2019-12-25 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20191202_0629'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonusQuestion',
            fields=[
                ('level_id', models.IntegerField(primary_key=True, serialize=False)),
                ('question', models.TextField(max_length=600)),
                ('answer', models.CharField(max_length=120)),
                ('expiration_date', models.DateTimeField()),
                ('live_date', models.DateTimeField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='static')),
                ('audiofile', models.FileField(blank=True, null=True, upload_to='static/', verbose_name='')),
                ('videofile', models.FileField(blank=True, null=True, upload_to='static/', verbose_name='')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='level',
            name='is_bonus',
        ),
        migrations.AlterField(
            model_name='level',
            name='answer',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='level',
            name='level_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='level',
            name='question',
            field=models.TextField(max_length=500),
        ),
    ]
